// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/port/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/port/ports.go -destination=internal/domain/port/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/spiehdid/crypto-price-aggregator/internal/domain/model"
	port "github.com/spiehdid/crypto-price-aggregator/internal/domain/port"
	gomock "go.uber.org/mock/gomock"
)

// MockPriceProvider is a mock of PriceProvider interface.
type MockPriceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPriceProviderMockRecorder
	isgomock struct{}
}

// MockPriceProviderMockRecorder is the mock recorder for MockPriceProvider.
type MockPriceProviderMockRecorder struct {
	mock *MockPriceProvider
}

// NewMockPriceProvider creates a new mock instance.
func NewMockPriceProvider(ctrl *gomock.Controller) *MockPriceProvider {
	mock := &MockPriceProvider{ctrl: ctrl}
	mock.recorder = &MockPriceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceProvider) EXPECT() *MockPriceProviderMockRecorder {
	return m.recorder
}

// GetPrice mocks base method.
func (m *MockPriceProvider) GetPrice(ctx context.Context, coinID, currency string) (*model.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", ctx, coinID, currency)
	ret0, _ := ret[0].(*model.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockPriceProviderMockRecorder) GetPrice(ctx, coinID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockPriceProvider)(nil).GetPrice), ctx, coinID, currency)
}

// GetPrices mocks base method.
func (m *MockPriceProvider) GetPrices(ctx context.Context, coinIDs []string, currency string) ([]model.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrices", ctx, coinIDs, currency)
	ret0, _ := ret[0].([]model.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrices indicates an expected call of GetPrices.
func (mr *MockPriceProviderMockRecorder) GetPrices(ctx, coinIDs, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrices", reflect.TypeOf((*MockPriceProvider)(nil).GetPrices), ctx, coinIDs, currency)
}

// Name mocks base method.
func (m *MockPriceProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPriceProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPriceProvider)(nil).Name))
}

// Status mocks base method.
func (m *MockPriceProvider) Status() *model.ProviderStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(*model.ProviderStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockPriceProviderMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockPriceProvider)(nil).Status))
}

// MockStreamProvider is a mock of StreamProvider interface.
type MockStreamProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStreamProviderMockRecorder
	isgomock struct{}
}

// MockStreamProviderMockRecorder is the mock recorder for MockStreamProvider.
type MockStreamProviderMockRecorder struct {
	mock *MockStreamProvider
}

// NewMockStreamProvider creates a new mock instance.
func NewMockStreamProvider(ctrl *gomock.Controller) *MockStreamProvider {
	mock := &MockStreamProvider{ctrl: ctrl}
	mock.recorder = &MockStreamProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamProvider) EXPECT() *MockStreamProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStreamProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStreamProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStreamProvider)(nil).Close))
}

// Subscribe mocks base method.
func (m *MockStreamProvider) Subscribe(ctx context.Context, coinIDs []string, currency string) (<-chan model.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, coinIDs, currency)
	ret0, _ := ret[0].(<-chan model.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockStreamProviderMockRecorder) Subscribe(ctx, coinIDs, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockStreamProvider)(nil).Subscribe), ctx, coinIDs, currency)
}

// MockPriceStore is a mock of PriceStore interface.
type MockPriceStore struct {
	ctrl     *gomock.Controller
	recorder *MockPriceStoreMockRecorder
	isgomock struct{}
}

// MockPriceStoreMockRecorder is the mock recorder for MockPriceStore.
type MockPriceStoreMockRecorder struct {
	mock *MockPriceStore
}

// NewMockPriceStore creates a new mock instance.
func NewMockPriceStore(ctrl *gomock.Controller) *MockPriceStore {
	mock := &MockPriceStore{ctrl: ctrl}
	mock.recorder = &MockPriceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceStore) EXPECT() *MockPriceStoreMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockPriceStore) GetHistory(ctx context.Context, coinID, currency string, from, to time.Time) ([]model.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, coinID, currency, from, to)
	ret0, _ := ret[0].([]model.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockPriceStoreMockRecorder) GetHistory(ctx, coinID, currency, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockPriceStore)(nil).GetHistory), ctx, coinID, currency, from, to)
}

// GetLatest mocks base method.
func (m *MockPriceStore) GetLatest(ctx context.Context, coinID, currency string) (*model.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatest", ctx, coinID, currency)
	ret0, _ := ret[0].(*model.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatest indicates an expected call of GetLatest.
func (mr *MockPriceStoreMockRecorder) GetLatest(ctx, coinID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatest", reflect.TypeOf((*MockPriceStore)(nil).GetLatest), ctx, coinID, currency)
}

// GetOHLC mocks base method.
func (m *MockPriceStore) GetOHLC(ctx context.Context, coinID, currency string, from, to time.Time, interval time.Duration) ([]model.OHLC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOHLC", ctx, coinID, currency, from, to, interval)
	ret0, _ := ret[0].([]model.OHLC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOHLC indicates an expected call of GetOHLC.
func (mr *MockPriceStoreMockRecorder) GetOHLC(ctx, coinID, currency, from, to, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOHLC", reflect.TypeOf((*MockPriceStore)(nil).GetOHLC), ctx, coinID, currency, from, to, interval)
}

// Save mocks base method.
func (m *MockPriceStore) Save(ctx context.Context, price *model.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPriceStoreMockRecorder) Save(ctx, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPriceStore)(nil).Save), ctx, price)
}

// SaveBatch mocks base method.
func (m *MockPriceStore) SaveBatch(ctx context.Context, prices []model.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, prices)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockPriceStoreMockRecorder) SaveBatch(ctx, prices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockPriceStore)(nil).SaveBatch), ctx, prices)
}

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCache) Delete(ctx context.Context, coinID, currency string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, coinID, currency)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheMockRecorder) Delete(ctx, coinID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCache)(nil).Delete), ctx, coinID, currency)
}

// Get mocks base method.
func (m *MockCache) Get(ctx context.Context, coinID, currency string) (*model.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, coinID, currency)
	ret0, _ := ret[0].(*model.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(ctx, coinID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), ctx, coinID, currency)
}

// Set mocks base method.
func (m *MockCache) Set(ctx context.Context, price *model.Price, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, price, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(ctx, price, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), ctx, price, ttl)
}

// MockProviderRouter is a mock of ProviderRouter interface.
type MockProviderRouter struct {
	ctrl     *gomock.Controller
	recorder *MockProviderRouterMockRecorder
	isgomock struct{}
}

// MockProviderRouterMockRecorder is the mock recorder for MockProviderRouter.
type MockProviderRouterMockRecorder struct {
	mock *MockProviderRouter
}

// NewMockProviderRouter creates a new mock instance.
func NewMockProviderRouter(ctrl *gomock.Controller) *MockProviderRouter {
	mock := &MockProviderRouter{ctrl: ctrl}
	mock.recorder = &MockProviderRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderRouter) EXPECT() *MockProviderRouterMockRecorder {
	return m.recorder
}

// ReportFailure mocks base method.
func (m *MockProviderRouter) ReportFailure(provider string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportFailure", provider, err)
}

// ReportFailure indicates an expected call of ReportFailure.
func (mr *MockProviderRouterMockRecorder) ReportFailure(provider, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportFailure", reflect.TypeOf((*MockProviderRouter)(nil).ReportFailure), provider, err)
}

// ReportSuccess mocks base method.
func (m *MockProviderRouter) ReportSuccess(provider string, latency time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportSuccess", provider, latency)
}

// ReportSuccess indicates an expected call of ReportSuccess.
func (mr *MockProviderRouterMockRecorder) ReportSuccess(provider, latency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportSuccess", reflect.TypeOf((*MockProviderRouter)(nil).ReportSuccess), provider, latency)
}

// Select mocks base method.
func (m *MockProviderRouter) Select(ctx context.Context, coinID string) (port.PriceProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, coinID)
	ret0, _ := ret[0].(port.PriceProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockProviderRouterMockRecorder) Select(ctx, coinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockProviderRouter)(nil).Select), ctx, coinID)
}

// MockTokenPriceProvider is a mock of TokenPriceProvider interface.
type MockTokenPriceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTokenPriceProviderMockRecorder
	isgomock struct{}
}

// MockTokenPriceProviderMockRecorder is the mock recorder for MockTokenPriceProvider.
type MockTokenPriceProviderMockRecorder struct {
	mock *MockTokenPriceProvider
}

// NewMockTokenPriceProvider creates a new mock instance.
func NewMockTokenPriceProvider(ctrl *gomock.Controller) *MockTokenPriceProvider {
	mock := &MockTokenPriceProvider{ctrl: ctrl}
	mock.recorder = &MockTokenPriceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenPriceProvider) EXPECT() *MockTokenPriceProviderMockRecorder {
	return m.recorder
}

// GetPriceByAddress mocks base method.
func (m *MockTokenPriceProvider) GetPriceByAddress(ctx context.Context, chain, address, currency string) (*model.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceByAddress", ctx, chain, address, currency)
	ret0, _ := ret[0].(*model.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceByAddress indicates an expected call of GetPriceByAddress.
func (mr *MockTokenPriceProviderMockRecorder) GetPriceByAddress(ctx, chain, address, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceByAddress", reflect.TypeOf((*MockTokenPriceProvider)(nil).GetPriceByAddress), ctx, chain, address, currency)
}

// SupportsChain mocks base method.
func (m *MockTokenPriceProvider) SupportsChain(chain string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsChain", chain)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsChain indicates an expected call of SupportsChain.
func (mr *MockTokenPriceProviderMockRecorder) SupportsChain(chain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsChain", reflect.TypeOf((*MockTokenPriceProvider)(nil).SupportsChain), chain)
}

// MockAnalyticsStore is a mock of AnalyticsStore interface.
type MockAnalyticsStore struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsStoreMockRecorder
	isgomock struct{}
}

// MockAnalyticsStoreMockRecorder is the mock recorder for MockAnalyticsStore.
type MockAnalyticsStoreMockRecorder struct {
	mock *MockAnalyticsStore
}

// NewMockAnalyticsStore creates a new mock instance.
func NewMockAnalyticsStore(ctrl *gomock.Controller) *MockAnalyticsStore {
	mock := &MockAnalyticsStore{ctrl: ctrl}
	mock.recorder = &MockAnalyticsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsStore) EXPECT() *MockAnalyticsStoreMockRecorder {
	return m.recorder
}

// PriceAnomalies mocks base method.
func (m *MockAnalyticsStore) PriceAnomalies(ctx context.Context, coinID, currency string, deviationPercent float64, from, to time.Time) ([]model.PriceAnomaly, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceAnomalies", ctx, coinID, currency, deviationPercent, from, to)
	ret0, _ := ret[0].([]model.PriceAnomaly)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PriceAnomalies indicates an expected call of PriceAnomalies.
func (mr *MockAnalyticsStoreMockRecorder) PriceAnomalies(ctx, coinID, currency, deviationPercent, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceAnomalies", reflect.TypeOf((*MockAnalyticsStore)(nil).PriceAnomalies), ctx, coinID, currency, deviationPercent, from, to)
}

// PriceStats mocks base method.
func (m *MockAnalyticsStore) PriceStats(ctx context.Context, coinID, currency string, from, to time.Time) (*model.PriceStatsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceStats", ctx, coinID, currency, from, to)
	ret0, _ := ret[0].(*model.PriceStatsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PriceStats indicates an expected call of PriceStats.
func (mr *MockAnalyticsStoreMockRecorder) PriceStats(ctx, coinID, currency, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceStats", reflect.TypeOf((*MockAnalyticsStore)(nil).PriceStats), ctx, coinID, currency, from, to)
}

// ProviderAccuracy mocks base method.
func (m *MockAnalyticsStore) ProviderAccuracy(ctx context.Context, from, to time.Time) ([]model.ProviderAccuracyReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderAccuracy", ctx, from, to)
	ret0, _ := ret[0].([]model.ProviderAccuracyReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProviderAccuracy indicates an expected call of ProviderAccuracy.
func (mr *MockAnalyticsStoreMockRecorder) ProviderAccuracy(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderAccuracy", reflect.TypeOf((*MockAnalyticsStore)(nil).ProviderAccuracy), ctx, from, to)
}

// VolumeByProvider mocks base method.
func (m *MockAnalyticsStore) VolumeByProvider(ctx context.Context, from, to time.Time) ([]model.ProviderVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeByProvider", ctx, from, to)
	ret0, _ := ret[0].([]model.ProviderVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VolumeByProvider indicates an expected call of VolumeByProvider.
func (mr *MockAnalyticsStoreMockRecorder) VolumeByProvider(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeByProvider", reflect.TypeOf((*MockAnalyticsStore)(nil).VolumeByProvider), ctx, from, to)
}
